language: python
python: 2.7
env:
  matrix:
    - TOXENV=flakes
    - TOXENV=py26-dj1.6
    - TOXENV=py27-dj1.6
    - TOXENV=py27-dj1.7
    - TOXENV=py33-dj1.6
    - TOXENV=py33-dj1.7
    - TOXENV=py34-dj1.6
    - TOXENV=py34-dj1.7
before_install:
  - npm install -g coffee-script
  - npm install -g less@1.7.4
  - npm install -g babel@4.3.0
  - npm install -g stylus@0.50.0
  - gem install sass --version 3.3.14
  - gem install compass --version 1.0.1
script:
  coverage run --source=static_precompiler `which tox`
install:
  - pip install tox
  - pip install coveralls
after_success:
  coveralls
