version: 2
jobs:
  build:
    working_directory: ~/django-static-precompiler
    docker:
      - image: andreyfedoseev/django-static-precompiler
    steps:
      - run: apt-get -y install software-properties-common && apt-get -y update
      - run: add-apt-repository ppa:deadsnakes/ppa -y && apt-get -y update
      - run: apt-get install -y python2.7-dev python3.6-dev python-pip sqlite3
      - checkout
      - run: pip install --upgrade pip
      - run: pip install -r requirements-ci.txt
      - run: pip install -e .[libsass]
      - run: flake8
      - run: rm -f coverage.xml
      - run: tox
      - run: codecov
